
POST http://localhost:8000/api/v1/products
Content-Type: application/json

{   
       "image": "https://s3-us-west-2.amazonaws.com/s.cdpn.io/1315882/zoom-fly-3-premium-mens-running-shoe-XhzpPH-removebg-preview.png",
      "name": "Nike Zoom Fly 3 Premium",
      "description": "Inspired by the Vaporfly, the Nike Zoom Fly 3 Premium gives distance runners race-day comfort and durability. The power of a carbon fiber plate keeps you in the running mile after mile.",
      "price": 160.0,
      "color": "#54D4C9"
  
}
###    

GET http://localhost:8000/api/v1/products
###
GET http://localhost:8000/api/v1/products/656f2009d7043b1342ba28fa
###

DELETE  http://localhost:8000/api/v1/products/656f2009d7043b1342ba28fa
###

PUT   http://localhost:8000/api/v1/products/656f2009d7043b1342ba28fa
Content-Type: application/json

{   
   "name": "Nike Vaporfly 4% Flyknit"
}

##########################################

POST http://localhost:8000/api/v1/carts
Content-Type: application/json

{   
       "userId":1
}
###    

GET http://localhost:8000/api/v1/carts
###
GET http://localhost:8000/api/v1/carts/1
###

###
patch   http://localhost:8000/api/v1/carts/addProducts/1
Content-Type: application/json

{   
   "_id": "656f1f9b44d094b201c75e11",
  "image": "https://s3-us-west-2.amazonaws.com/s.cdpn.io/1315882/air-zoom-pegasus-36-mens-running-shoe-wide-D24Mcz-removebg-preview.png",
  "name": "Nike Air Zoom Pegasus 36",
  "description": "The iconic Nike Air Zoom Pegasus 36 offers more cooling and mesh that targets breathability across high-heat areas. A slimmer heel collar and tongue reduce bulk, while exposed cables give you a snug fit at higher speeds.",
  "price": 108.97,
  "color": "#e1e7ed",
  "quantity":4
}

###
patch   http://localhost:8000/api/v1/carts/removeProducts/1/656f1f9b44d094b201c75e11


###
patch   http://localhost:8000/api/v1/carts/editProducts/1
Content-Type: application/json

{   
   "_id": "656f1f9b44d094b201c75e12",
  "quantity": 0
}